apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: praveen-test
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "5"
    pods: "10"
