apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: praveen-test
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd123
  ME_CONFIG_BASICAUTH_PASSWORD: P@ssw0rd123
